# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoStudentClass.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(521, 310)
        self.labelOutput = QtWidgets.QLabel(Dialog)
        self.labelOutput.setGeometry(QtCore.QRect(20, 220, 451, 20))
        self.labelOutput.setObjectName("labelOutput")
        self.lineEditName = QtWidgets.QLineEdit(Dialog)
        self.lineEditName.setGeometry(QtCore.QRect(210, 30, 113, 25))
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditCod = QtWidgets.QLineEdit(Dialog)
        self.lineEditCod.setGeometry(QtCore.QRect(210, 80, 113, 25))
        self.lineEditCod.setObjectName("lineEditCod")
        self.labelName = QtWidgets.QLabel(Dialog)
        self.labelName.setGeometry(QtCore.QRect(100, 30, 67, 17))
        self.labelName.setObjectName("labelName")
        self.labelCod = QtWidgets.QLabel(Dialog)
        self.labelCod.setGeometry(QtCore.QRect(100, 80, 67, 17))
        self.labelCod.setObjectName("labelCod")
        self.pushButtonClick = QtWidgets.QPushButton(Dialog)
        self.pushButtonClick.setGeometry(QtCore.QRect(160, 170, 89, 25))
        self.pushButtonClick.setObjectName("pushButtonClick")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelOutput.setText(_translate("Dialog", "TextLabel"))
        self.labelName.setText(_translate("Dialog", "Nombre"))
        self.labelCod.setText(_translate("Dialog", "Codigo"))
        self.pushButtonClick.setText(_translate("Dialog", "Imprimir"))
