# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoMultipleInheritance.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(546, 430)
        self.labelName = QtWidgets.QLabel(Dialog)
        self.labelName.setGeometry(QtCore.QRect(90, 20, 67, 17))
        self.labelName.setObjectName("labelName")
        self.labelCode = QtWidgets.QLabel(Dialog)
        self.labelCode.setGeometry(QtCore.QRect(90, 60, 67, 17))
        self.labelCode.setObjectName("labelCode")
        self.labelkgMaiz = QtWidgets.QLabel(Dialog)
        self.labelkgMaiz.setGeometry(QtCore.QRect(90, 100, 81, 20))
        self.labelkgMaiz.setObjectName("labelkgMaiz")
        self.labelkgCafe = QtWidgets.QLabel(Dialog)
        self.labelkgCafe.setGeometry(QtCore.QRect(90, 130, 67, 17))
        self.labelkgCafe.setObjectName("labelkgCafe")
        self.labelkgTotal = QtWidgets.QLabel(Dialog)
        self.labelkgTotal.setGeometry(QtCore.QRect(90, 170, 67, 17))
        self.labelkgTotal.setObjectName("labelkgTotal")
        self.labelRazon = QtWidgets.QLabel(Dialog)
        self.labelRazon.setGeometry(QtCore.QRect(36, 210, 121, 20))
        self.labelRazon.setObjectName("labelRazon")
        self.lineEditName = QtWidgets.QLineEdit(Dialog)
        self.lineEditName.setGeometry(QtCore.QRect(190, 20, 113, 25))
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditCode = QtWidgets.QLineEdit(Dialog)
        self.lineEditCode.setGeometry(QtCore.QRect(190, 60, 113, 25))
        self.lineEditCode.setObjectName("lineEditCode")
        self.lineEditkgMaiz = QtWidgets.QLineEdit(Dialog)
        self.lineEditkgMaiz.setGeometry(QtCore.QRect(190, 100, 113, 25))
        self.lineEditkgMaiz.setObjectName("lineEditkgMaiz")
        self.lineEditkgCafe = QtWidgets.QLineEdit(Dialog)
        self.lineEditkgCafe.setGeometry(QtCore.QRect(190, 130, 113, 25))
        self.lineEditkgCafe.setObjectName("lineEditkgCafe")
        self.lineEditkgTotal = QtWidgets.QLineEdit(Dialog)
        self.lineEditkgTotal.setEnabled(False)
        self.lineEditkgTotal.setGeometry(QtCore.QRect(190, 170, 331, 25))
        self.lineEditkgTotal.setObjectName("lineEditkgTotal")
        self.lineEditRazon = QtWidgets.QLineEdit(Dialog)
        self.lineEditRazon.setEnabled(False)
        self.lineEditRazon.setGeometry(QtCore.QRect(190, 210, 331, 25))
        self.lineEditRazon.setObjectName("lineEditRazon")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(200, 260, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.labelOutput = QtWidgets.QLabel(Dialog)
        self.labelOutput.setGeometry(QtCore.QRect(20, 316, 481, 31))
        self.labelOutput.setObjectName("labelOutput")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.labelName.setText(_translate("Dialog", "Name"))
        self.labelCode.setText(_translate("Dialog", "Code"))
        self.labelkgMaiz.setText(_translate("Dialog", "kg Maiz"))
        self.labelkgCafe.setText(_translate("Dialog", "kg Cafe"))
        self.labelkgTotal.setText(_translate("Dialog", "Total Kg"))
        self.labelRazon.setText(_translate("Dialog", "Razon cafe/maiz"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
        self.labelOutput.setText(_translate("Dialog", "TextLabel"))
