# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QCheckBoxes.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 10, 191, 20))
        self.label.setObjectName("label")
        self.radioButtonCh = QtWidgets.QRadioButton(Dialog)
        self.radioButtonCh.setGeometry(QtCore.QRect(120, 50, 112, 23))
        self.radioButtonCh.setObjectName("radioButtonCh")
        self.buttonGroupTama = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroupTama.setObjectName("buttonGroupTama")
        self.buttonGroupTama.addButton(self.radioButtonCh)
        self.radioButtonMed = QtWidgets.QRadioButton(Dialog)
        self.radioButtonMed.setGeometry(QtCore.QRect(120, 80, 112, 23))
        self.radioButtonMed.setObjectName("radioButtonMed")
        self.buttonGroupTama.addButton(self.radioButtonMed)
        self.radioButtonGra = QtWidgets.QRadioButton(Dialog)
        self.radioButtonGra.setGeometry(QtCore.QRect(120, 110, 112, 23))
        self.radioButtonGra.setObjectName("radioButtonGra")
        self.buttonGroupTama.addButton(self.radioButtonGra)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(90, 160, 151, 17))
        self.label_2.setObjectName("label_2")
        self.checkBoxQueso = QtWidgets.QCheckBox(Dialog)
        self.checkBoxQueso.setGeometry(QtCore.QRect(20, 200, 92, 23))
        self.checkBoxQueso.setObjectName("checkBoxQueso")
        self.checkBox_Peperoni = QtWidgets.QCheckBox(Dialog)
        self.checkBox_Peperoni.setGeometry(QtCore.QRect(140, 200, 92, 23))
        self.checkBox_Peperoni.setObjectName("checkBox_Peperoni")
        self.checkBox_Pina = QtWidgets.QCheckBox(Dialog)
        self.checkBox_Pina.setGeometry(QtCore.QRect(280, 200, 92, 23))
        self.checkBox_Pina.setObjectName("checkBox_Pina")
        self.labelOutput = QtWidgets.QLabel(Dialog)
        self.labelOutput.setGeometry(QtCore.QRect(30, 250, 331, 17))
        self.labelOutput.setText("")
        self.labelOutput.setObjectName("labelOutput")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Elija el tamaño de su Pizza"))
        self.radioButtonCh.setText(_translate("Dialog", "Chica"))
        self.radioButtonMed.setText(_translate("Dialog", "Mediana"))
        self.radioButtonGra.setText(_translate("Dialog", "Grande"))
        self.label_2.setText(_translate("Dialog", "Elija los ingrediente"))
        self.checkBoxQueso.setText(_translate("Dialog", "Queso"))
        self.checkBox_Peperoni.setText(_translate("Dialog", "Peperoni"))
        self.checkBox_Pina.setText(_translate("Dialog", "Piña"))
