# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoSimpleInheritance.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Coordenadas(object):
    def setupUi(self, Coordenadas):
        Coordenadas.setObjectName("Coordenadas")
        Coordenadas.resize(539, 318)
        self.labelName = QtWidgets.QLabel(Coordenadas)
        self.labelName.setGeometry(QtCore.QRect(90, 40, 67, 17))
        self.labelName.setObjectName("labelName")
        self.labelCod = QtWidgets.QLabel(Coordenadas)
        self.labelCod.setGeometry(QtCore.QRect(90, 80, 67, 17))
        self.labelCod.setObjectName("labelCod")
        self.labelX = QtWidgets.QLabel(Coordenadas)
        self.labelX.setGeometry(QtCore.QRect(90, 120, 67, 17))
        self.labelX.setObjectName("labelX")
        self.labelY = QtWidgets.QLabel(Coordenadas)
        self.labelY.setGeometry(QtCore.QRect(90, 150, 67, 17))
        self.labelY.setObjectName("labelY")
        self.lineEditName = QtWidgets.QLineEdit(Coordenadas)
        self.lineEditName.setGeometry(QtCore.QRect(230, 40, 113, 25))
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditCod = QtWidgets.QLineEdit(Coordenadas)
        self.lineEditCod.setGeometry(QtCore.QRect(230, 80, 113, 25))
        self.lineEditCod.setObjectName("lineEditCod")
        self.lineEditX = QtWidgets.QLineEdit(Coordenadas)
        self.lineEditX.setGeometry(QtCore.QRect(230, 120, 113, 25))
        self.lineEditX.setObjectName("lineEditX")
        self.lineEditY = QtWidgets.QLineEdit(Coordenadas)
        self.lineEditY.setGeometry(QtCore.QRect(230, 160, 113, 25))
        self.lineEditY.setObjectName("lineEditY")
        self.pushButtonImprime = QtWidgets.QPushButton(Coordenadas)
        self.pushButtonImprime.setGeometry(QtCore.QRect(180, 210, 89, 25))
        self.pushButtonImprime.setObjectName("pushButtonImprime")
        self.labelOutput = QtWidgets.QLabel(Coordenadas)
        self.labelOutput.setGeometry(QtCore.QRect(30, 250, 481, 20))
        self.labelOutput.setObjectName("labelOutput")

        self.retranslateUi(Coordenadas)
        QtCore.QMetaObject.connectSlotsByName(Coordenadas)

    def retranslateUi(self, Coordenadas):
        _translate = QtCore.QCoreApplication.translate
        Coordenadas.setWindowTitle(_translate("Coordenadas", "Dialog"))
        self.labelName.setText(_translate("Coordenadas", "Nombre"))
        self.labelCod.setText(_translate("Coordenadas", "Codigo"))
        self.labelX.setText(_translate("Coordenadas", "Mark X"))
        self.labelY.setText(_translate("Coordenadas", "Mark Y"))
        self.pushButtonImprime.setText(_translate("Coordenadas", "Imprimir"))
        self.labelOutput.setText(_translate("Coordenadas", "TextLabel"))
